### PR TITLE
Add support for firebase admin

### PR DESCRIPTION
**Pull request by guybedford**
I finally managed to found an approach to fix the google-gax `.proto` file asset handling.

It turned out to be a surprisingly simple special case in the end.

### CODE REVIEW

**Comment by MAPESO** [comment]
Awesome !!  @guybedford Thank you  ❤️

**Comment by leerob** [comment]
Has this fix been released? I'm still seeing issues with proto files using the `@now/node` builder.

**Comment by styfle** [comment]
Yes, it's been released to the canary branch.

Try using `@now/node@canary` in your `now.json` file.

**Comment by MAPESO** [comment]
@leerob If you intend to use **firebase-admin** in`now` or `now dev`, the truth is that it still does not work. At the moment it only works in `ncc` but we are investigating the root of the problem to be able to solve it 🙏 😸

**Comment by leerob** [comment]
What makes no sense to me is that it _does work_ locally from the CLI, but not using the Now integration for GitHub (on PRs). 

I can try to get an example up, but it's a simple express API serverless using Firebase with one route.

**Comment by styfle** [comment]
Perhaps this is the issue you are seeing? https://github.com/zeit/ncc/issues/367

**Comment by diogoviannaaraujo** [comment]
I still get this error using @now/next@canary

**Pull request merged**
